### ISSUE TITLE
Repository standardization

### ISSUE THREAD

**Issue by luxonauta** [dracula/youtube#1]
Hi @leozz37, we need to adjust a few things first to move forward, ok? ✨

You must write the installation steps in the [INSTALL.md](https://github.com/dracula/youtube/blob/main/INSTALL.md) file, as it will appear on the site when a user searches for this theme.

Let me know if something isn't possible or if you have any questions! 🙂

**Comment by leozz37** [comment]
Hey @luxonauta! Just opened a PR for this! #2
